name: bananny
description: A new Flutter project for kids

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  flutter_pdfview: ^1.2.7
  curved_navigation_bar: ^1.0.3
  vertical_card_pager: ^1.5.0
  scribble: ^0.9.1
  flutter_state_notifier: ^0.7.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.0.18
  flutter_jigsaw_puzzle: 
    git: https://github.com/vovaguru/flutter_jigsaw_puzzle.git
  flutter_launcher_icons: "^0.12.0"
  flutter_native_splash: ^2.2.19
  path_provider: ^2.0.14
  pdfx: ^2.3.0
  syncfusion_flutter_pdfviewer: ^20.4.54

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  fonts:
          - family: AtypText
            fonts: 
              - asset: fonts/AtypText-Medium.ttf
  assets:
    - assets/images/
    - assets/

